apiVersion: v2
name: ehrbase
version: 0.1.0
description: A Helm chart for deploying EHRbase on Kubernetes
type: application
dependencies:
  - name: cluster
    version: 0.6.1
    repository: https://cloudnative-pg.github.io/charts
    condition: cnpg.enabled
    alias: cnpg
maintainers:
  - name: Tourbillon
    url: https://tourbillon.health
# renovate: image=ehrbase/ehrbase
appVersion: "2.31.0"
