{{- if and .Values.config.basicAuth.enabled (not .Values.config.basicAuth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ehrbase.fullname" . }}
  labels:
    {{- include "ehrbase.labels" . | nindent 4 }}
data:
  admin-username: {{ .Values.config.basicAuth.adminUsername | b64enc }}
  admin-password: {{ .Values.config.basicAuth.adminPassword | b64enc }}
  username: {{ .Values.config.basicAuth.username | b64enc }}
  password: {{ .Values.config.basicAuth.password | b64enc }}
{{- end }}
